### ISSUE TITLE
Build Project Page frontend for our first charity

### ISSUE THREAD

**Issue by MKagesawa** [nyu-software-engineering/Laika#37]
User Story: https://github.com/nyu-software-engineering/Laika/issues/4

**Comment by rachelrios** [comment]
@SeanSCao  Can you go into charities, select one and create a fake profile for it? Currently it is a zoom in card with a button that says "Donate". Could you create either a dropdown or an external page that tells users more info about the charity once they click on donate? Lets use Brooklyn animal action to test. http://brooklynanimalaction.org
