### ISSUE TITLE
Built About page explaining the value of our product

### ISSUE THREAD

**Issue by MKagesawa** [nyu-software-engineering/Laika#52]
User Story #3 
- Use links, videos, articles of external resources.
Do not waste time explaining Ethereum, Blockchain, dApps yourself. There are plenty of resources out there

**Comment by rachelrios** [comment]
@sillyangela Can you go into the tutorial page and fill out the info on "Why Laika?" and explain our product like you would to someone who does not know what crypto is? I have set up a template, all you have to do is format and enter text.
