### ISSUE TITLE
Integrate front-end to backend

### ISSUE THREAD

**Issue by MKagesawa** [nyu-software-engineering/Laika#60]
User Story: https://github.com/nyu-software-engineering/Laika/issues/4

**Comment by rachelrios** [comment]
This needs to be pushed to sprint 2, there are many moving parts that we need to tie down back and pages we are missing. It is not as simple as we thought . Currently a market place can select things to buy on a test network but we need to talk on how to set up a donation page for donors to charities. 

Front End 
- Implement a key factor authentication  (or other solution) for charities to be able to purchase items: Current password is “smalldogs”
    - http://localhost:3000
(sprint 2/3)

Back End:
- Track Donation and Purchase Actions and Parse them as a JSON
(sprint 2/3)
Front end:
- Read these files and push it to a site for public to see (sprint 2/3)
