### ISSUE TITLE
As a developer I want to develop a fake currency to test the system

### ISSUE THREAD

**Issue by rachelrios** [nyu-software-engineering/Laika#8]
## Size
TBD

## Acceptance Criteria
- [x] Implement a crypto currency and research basics on how it interacts with our sysrem

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-crowd-donation - this is a spike, not a user story.  Please update the labels.  A user story is always something that directly affects the experience of an end-user.  A spike is an internal facing piece of work that is not directly related to a user story.

Every issue on your task board should be assigned to one or more team members, and should be marked with the milestone for the sprint that the task board represents.
